Enable running ansible-test via Podman
ansible/galaxy-importer pull request #100
Opened 2020-11-05 21:46 UTC by bmclaughlin

Enables running `ansible-test` via Podman when setting the following in `galaxy-importer.cfg`:
```
RUN_ANSIBLE_TEST=True
ANSIBLE_TEST_LOCAL_IMAGE=True
LOCAL_IMAGE_DOCKER=False
```
Need to finish finish PR that installs the dependencies in `galaxy_ng`
Need to update `readme.md` to reflect the settings changes

Issue: AAH-5

2020-11-05 21:51 UTC, bmclaughlin commented
@awcrosby, `Dockerfile.local` and `entrypoint-local.sh` and the associated update to the `_build_dockerfile()` method are workarounds for AAH-89.

2020-11-11 20:10 UTC, awcrosby approved these changes

2020-11-11 21:51 UTC, awcrosby requested changes
@bmclaughlin thinking more, we probably should have a binary check like other places in the importer, which exits the runner if not installed
```
        if not shutil.which(self.container_engine):
            self.log.warning(f'"{self.container_engine}" not found, skipping ansible-test sanity')
            return
```

2020-11-13 13:50 UTC, bmclaughlin commented on galaxy_importer/ansible_test/builders/local_image_build.py
> +        cmd = [container_engine, 'build', '.', '--quiet']
Looks like caching is not currently supported, from the `podman` docs at [1]:
```
–cache-from
Images to utilize as potential cache sources. Podman does not currently support caching so this is a NOOP.
```
[1] http://docs.podman.io/en/latest/markdown/podman-build.1.html

2020-11-13 19:17 UTC, awcrosby approved these changes

2020-11-13 19:32 UTC, merged