Make root temp directory configurable
ansible/galaxy-importer pull request #94
Opened 2020-10-26 16:30 UTC by bmclaughlin

Issue: https://issues.redhat.com/browse/AAH-91

2020-10-26 20:38 UTC, awcrosby approved these changes

2020-10-27 09:17 UTC, Spredzy commented
This works as expected, but is not enough to fix  https://issues.redhat.com/browse/AAH-91.

In order to fix it, in addition to be able to specify `TMP_ROOT_DIR`  we need to be able to specify `ANSIBLE_LOCAL_TEMP`[1]

This is used by `ansible-doc` to do its duties. So, in a SELinux environment, we may want to specify an `ANSIBLE_LOCAL_TEMP` that has the proper labelling (vs. default `${HOME}/.ansible/tmp` which might not have it)

```
[root@ip-10-0-10-175 ec2-user]# strace ansible-doc file 2>&1 | grep tmp
stat("/root/.ansible/tmp", {st_mode=S_IFDIR|0700, st_size=6, ...}) = 0
mkdir("/root/.ansible/tmp/ansible-local-22084mwnRCW", 0700) = 0
```

Now there are two ways we can do this:

  * **The opinionated way**: Given we are already specifying `TMP_ROOT_DIR` we know that the `collections_path` will have proper labelling, so we can be opinionated and reuse that here. No new configuration variable to add.

```path
diff --git galaxy_importer/loaders.py galaxy_importer/loaders.py
index 6900703..a911cc1 100644
--- galaxy_importer/loaders.py
+++ galaxy_importer/loaders.py
@@ -229,6 +229,7 @@ class DocStringLoader():
         collections_path = '/'.join(self.path.split('/')[:-3])
         cmd = [
             '/usr/bin/env', f'ANSIBLE_COLLECTIONS_PATHS={collections_path}',
+            f'ANSIBLE_LOCAL_TEMP={collections_path}
             'ansible-doc',
             '--type', plugin_type,
             '--json',
```

  * **The more flexible way**: Just like `TMP_ROOT_DIR` add a new `ANSIBLE_LOCAL_TEMP` in `[galaxy-importer]` section

[1] https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-local-tmp

2020-10-27 13:46 UTC, awcrosby commented
Either approach sounds ok to me

2020-10-27 20:30 UTC, awcrosby requested changes

2020-10-27 20:30 UTC, awcrosby commented on galaxy_importer/collection.py
> +        tmp_root_dir = cfg.tmp_root_dir
looking again at this, since we have a default config, `if cfg` will always resolve to true, recommend:
`tmp_root_dir = cfg.tmp_root_dir`

2020-10-27 20:30 UTC, awcrosby commented on galaxy_importer/loaders.py
> +            ansible_local_tmp = self.cfg.ansible_local_tmp
same here, with `self.cfg` always present, this probably should be
```ansible_local_tmp = self.cfg.ansible_local_tmp or '~/.ansible/tmp'```

2020-10-27 20:30 UTC, awcrosby commented on README.md
>  ```
probably worth adding the 2nd config option here

2020-10-27 21:22 UTC, awcrosby approved these changes

2020-10-27 21:46 UTC, merged